name: BuildAndTestOnEveryPush.yml

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build on windows-latest
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: dotnet build
    
    - name: Test
      env:
        HIQ_POSTGRES_CONNECTION_STRING:  ${{ secrets.HIQ_POSTGRES_CONNECTION_STRING }}
      run: dotnet test
      
    - name: Pack release version of task
      run: dotnet pack --configuration Release --include-source
      
    - name: Push NuGet package to the testfeed
      run: dotnet nuget push Frends.Community.Postgre\bin\Release\Frends.Community.Postgre.*.nupkg  --api-key ${{ secrets.COMMUNITY_FEED_API_KEY }} --source https://www.myget.org/F/frends-community-test/api/v2/package --symbol-source https://www.myget.org/F/frends-community-test/symbols/api/v2/package
